### ISSUE TITLE
Seems all swan interfaces are down.

### ISSUE THREAD

**Issue by fernvenue** [6-6-6/swan-updown#1]
As above, all my `swan*` interfaces are down, when I manually up, they all work well.

**Comment by fernvenue** [comment]
Here's my `swan-updown` version:

```
~# /usr/bin/swan-updown --version
swan-updown 0.2.7
```

**Comment by 6-6-6** [comment]
> As above, all my `swan*` interfaces are down, when I manually up, they all work well.

That seems critical...

Could you please run `swan-updown` with `-dd` and check `/var/log/user.log` ?
Maybe this would tell us what happens.

**Comment by fernvenue** [comment]
Thanks for your reply, I just tried to run `swan-updown` with `-dd`, shows `Error: ()` and `/var/log/user.log` is empty.

**Comment by 6-6-6** [comment]
> Thanks for your reply, I just tried to run `swan-updown` with `-dd`, shows `Error: ()`

It is expected, because `swan-updown`'s behaviour depends on `PLUTO_*` env variables.

Maybe you will need to update the arguments to your
```
connections.<conn>.children.<child>.updown =
```
line, and wait for something happening


> and `/var/log/user.log` is empty.

That's strange. I suppose there should be something like:
```
2024-01-07T21:18:34.555471+00:00 localhost swan-updown[42]: Environment variable PLUTO_VERB not found: environment variable not found, exiting...
```
logged to syslog ([see here](https://github.com/6-6-6/swan-updown/blob/a3db5a1160f010ab03f8fb2877f7cb5f8b944a33/src/main.rs#L59C22-L59C22))...
How is your syslog configured?

However, you can always add `--to-stdout` to ask it to print everything to stdout.
If this is your preference, please just do it this way.

**Comment by fernvenue** [comment]
Thanks for your reply, and I successfuly got the output message:

```
swan-updown[5145]: Environment variable PLUTO_VERB found: up-client
swan-updown[5145]: Environment variable PLUTO_IF_ID_IN found: 341
swan-updown[5145]: Environment variable PLUTO_MY_ID found: O=fernvenue, CN=FNT, serialNumber=1
swan-updown[5145]: Environment variable PLUTO_PEER_ID found: O=fernvenue, CN=HEL, serialNumber=1
swan-updown[5145]: Environment variable PLUTO_ME found: 1***5
swan-updown[5145]: Environment variable PLUTO_PEER found: 6***6
swan-updown[5145]: enabling module interface
swan-updown[5145]: get interface swan00000155, everything is ok
swan-updown[5151]: Environment variable PLUTO_VERB found: up-client-v6
swan-updown[5151]: Environment variable PLUTO_IF_ID_IN found: 341
swan-updown[5151]: Environment variable PLUTO_MY_ID found: O=fernvenue, CN=FNT, serialNumber=1
swan-updown[5151]: Environment variable PLUTO_PEER_ID found: O=fernvenue, CN=HEL, serialNumber=1
swan-updown[5151]: Environment variable PLUTO_ME found: 1***5
swan-updown[5151]: Environment variable PLUTO_PEER found: 6***6
swan-updown[5151]: enabling module interface
swan-updown[5151]: get interface swan00000155, everything is ok
```

But as you can see, `swan-updown` just said that `everything is ok`, actually these interfaces are `DOWN`, that's weird.

By the way, currently I use this instead:

```
#!/bin/bash

LINK=swan$(printf '%08x\n' "$PLUTO_IF_ID_OUT")
case "$PLUTO_VERB" in
    up-client)
        ip link add "$LINK" type xfrm if_id "$PLUTO_IF_ID_OUT"
        ip link set "$LINK" multicast on mtu 1420 up
        ;;
    down-client)
        ip link del "$LINK"
        ;;
esac
```

And it works fine for now.

**Comment by 6-6-6** [comment]
Hello,

> Le 9 janv. 2024 à 00:50, fernvenue ***@***.***> a écrit :
> 
> 
> Thanks for your reply, and I successfuly got the output message:
> 
> swan-updown[5145]: Environment variable PLUTO_VERB found: up-client
> swan-updown[5145]: Environment variable PLUTO_IF_ID_IN found: 341
> swan-updown[5145]: Environment variable PLUTO_MY_ID found: O=fernvenue, CN=FNT, serialNumber=1
> swan-updown[5145]: Environment variable PLUTO_PEER_ID found: O=fernvenue, CN=HEL, serialNumber=1
> swan-updown[5145]: Environment variable PLUTO_ME found: 1***5
> swan-updown[5145]: Environment variable PLUTO_PEER found: 6***6
> swan-updown[5145]: enabling module interface
> swan-updown[5145]: get interface swan00000155, everything is ok
> swan-updown[5151]: Environment variable PLUTO_VERB found: up-client-v6
> swan-updown[5151]: Environment variable PLUTO_IF_ID_IN found: 341
> swan-updown[5151]: Environment variable PLUTO_MY_ID found: O=fernvenue, CN=FNT, serialNumber=1
> swan-updown[5151]: Environment variable PLUTO_PEER_ID found: O=fernvenue, CN=HEL, serialNumber=1
> swan-updown[5151]: Environment variable PLUTO_ME found: 1***5
> swan-updown[5151]: Environment variable PLUTO_PEER found: 6***6
> swan-updown[5151]: enabling module interface
> swan-updown[5151]: get interface swan00000155, everything is ok
> But as you can see, swan-updown just said that everything is ok, actually these interfaces is DOWN, that's weird.
> 
Sorry that I actually misunderstood the bug…
I have to bring up the interface explicitly instead of just add a `LinkFlag::Up`.

Please refer to [8a5aea5787 <https://github.com/6-6-6/swan-updown/commit/8a5aea57875703b1296b00564b3885790d9e72ac>](https://github.com/6-6-6/swan-updown/commit/8a5aea57875703b1296b00564b3885790d9e72ac) which should fix this bug.

**Comment by fernvenue** [comment]
Hi @6-6-6, I just tested it, and it works perfectly fine, thanks! And I'm gonna close this issue for now :)
