### ISSUE TITLE
Debian package for arm64 too old?

### ISSUE THREAD

**Issue by fernvenue** [6-6-6/swan-updown#2]
Hi, I just updated `swan-updown` from `deb.kyouka.moe`, and amd64 version is already the latest version aka `0.2.8`, but arm64 is still in `0.2.5`. I think that will be great if we can use latest version on arm64 also :)

**Comment by 6-6-6** [comment]
Yes, sure.
I have cross-compiled and uploaded the arm64 package.

**Comment by fernvenue** [comment]
Thanks!
